# まとめ

## NumPy とは
* 科学計算のための基本的なパッケージ．
* 各種数学アルゴリズムや配列計算ライブラリを提供する
* このパッケージを利用して提供されているライブラリも各種存在する

## 情報源
* http://www.numpy.org/

# 使い方

## インポート

In [2]:
# NumPyのインポート
import numpy as np

## バージョン確認

In [10]:
# バージョンの確認
print(np.version.version)

1.14.0


## ベクトルや行列の生成
* ベクトルや行列は np.array メソッドで生成する.このメソッドにより np.ndarrayクラスが生成される．

### ベクトル

In [77]:
# リストから1次元の配列を生成
x = np.array([1,2,3])
print("x = ", x)

# データ型(クラス)の確認
print(x.__class__)
print(type(x))

# 配列の形状．1行3列．1は表示されない
# (1,3)と表示するのが自然な気がするが，(3,) と表示される
print("x.shape = ", x.shape)

# 次元数
print("x.dim = ", x.ndim)

x =  [1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
x.shape =  (3,)
x.dim =  1


### 行列
* 行列は2次元配列として表される
* 行の集まりのように表現

In [79]:
# リストから行列の生成．ネストされたリストを使う
# リスト型変数を使う場合は，[1,2,3] の部分がリスト型変数 t1 に置き換わる
W = np.array([[1,2,3],[4,5,6]])
print("W =", W)

# データ型(クラス)の確認
print("W.__class =",W.__class__)
print("type(W) =", type(W))

# 行列の形状(2行3列). 結果はタプルとして得られる
print("W.shape =", W.shape)
print("type(W.shape) :", type(W.shape))

# 次元数(2)
print("W.dim =", W.ndim)
print("type(W.ndim) :", type(W.ndim))

# 要素のデータ型を調べる
print("W.dtype =", W.dtype)

W = [[1 2 3]
 [4 5 6]]
W.__class = <class 'numpy.ndarray'>
type(W) = <class 'numpy.ndarray'>
W.shape = (2, 3)
type(W.shape) : <class 'tuple'>
W.dim = 2
type(W.ndim) : <class 'int'>
W.dtype = int64


In [ ]:
# 繰り返し
X = np.array([[51, 55], [14, 19], [0, 4]])
print("X =")
print(X)

# 行ごと
for row in X:
    print(row)

# 要素ごと


### テンソル

## 要素へのアクセス

* あとで読む
    * https://note.nkmk.me/python-numpy-condition/

### ベクトル

In [100]:
x = np.array([1,2,3,4,5,6])
print("x = ", x)

# 指定したインデックスの要素を取り出す
# インデックスの指定はリストとして与える
print("x[np.array([0, 2, 4])] =", x[np.array([0, 2, 4])])  # [1 3 5]
print("type(x[np.array([0, 2, 4])]) =", type(x[np.array([0, 2, 4])]))
print()

# 条件を満たす要素だけからなる配列の取得

# 4 より大きい値をもつ要素だけを取り出す
print("x[x>4] =", x[x>4]) # [5 6]
print("type(x[x>4]) =", type(x[x>4]))
print()

# 偶数の値をもつ要素だけを取り出す
print("x[x%2==0] =", x[x%2==0])    # [2 4 6]

# 最大，最小要素のインデックスを取り出す
print("x.argmax(axis=0) =", x.argmax(axis=0))
print("x.argmin(axis=0) =", x.argmin(axis=0))

x =  [1 2 3 4 5 6]
x[np.array([0, 2, 4])] = [1 3 5]
type(x[np.array([0, 2, 4])]) = <class 'numpy.ndarray'>

x[x>4] = [5 6]
type(x[x>4]) = <class 'numpy.ndarray'>

x[x%2==0] = [2 4 6]
x.argmax(axis=0) = 5
x.argmin(axis=0) = 0


### 行列

In [101]:
# 多次元配列の要素へのアクセス
X = np.array([[0, 55], [19, 14], [51, 4]])
print("X =")
print(X)

# 行単位
print("X[0] =", X[0])           # array([51, 55])

# 要素単位
print("X[0][1] =", X[0][1])     #55

# 最大要素のインデックス
print("X.argmax(axis=0) =", X.argmax(axis=0))  # 列方向
print("X.argmax(axis=1) =", X.argmax(axis=1))  # 行方向

# 最小要素のインデックス
print("X.argmin(axis=0) =", X.argmin(axis=0))  # 列方向
print("X.argmin(axis=1) =", X.argmin(axis=1))  # 行方向

X =
[[ 0 55]
 [19 14]
 [51  4]]
X[0] = [ 0 55]
X[0][1] = 55
X.argmax(axis=0) = [2 0]
X.argmax(axis=1) = [1 0 0]
X.argmin(axis=0) = [0 2]
X.argmin(axis=1) = [0 1 1]


### テンソル

## 行列の計算

### 行列の要素ごとの(element-wise)演算

In [18]:
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])
W + x

array([[2, 4, 6],
       [5, 7, 9]])

In [19]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

### ブロードキャスト
形状の異なる配列同士の計算

In [20]:
# ブロードキャストの例．Aと掛け算するために10という値は [[10,10],[10,10]] に拡張される．
A = np.array([[1,2],[3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [22]:
# ブロードキャストの例2．[10,20]という1次元配列は [[10,20],[10,20]] に拡張される．
A = np.array([[1,2],[3,4]])
b = np.array([10,20])
A * b

array([[10, 40],
       [30, 80]])

### ベクトルの内積と行列の積

* ベクトルの内積：2つのベクトル間の対応する要素の積の和
    * 直感的には**「2つのベクトルがどれだけ同じ方向を向いているか」**を表す

    $
    \bf{x}\cdot\bf{y} = x_1 y_1 + x_2 y_2 + ... + x_n y_n
    $

* 行列の積

    $
    \begin{equation}
        \begin{pmatrix}
            1 & 2\\
            3 & 4
        \end{pmatrix}
        \begin{pmatrix}
            5 & 6\\
            7 & 8
        \end{pmatrix}
        =
        \begin{pmatrix}
            a \cdot c & a \cdot d\\
            b \cdot c & b \cdot d
        \end{pmatrix}
        =
        \begin{pmatrix}
            19 & 22\\
            43 & 50
        \end{pmatrix}
    \end{equation}
    $

    ただしここで

        a = (1,2), b=(3,4), c=(5,7), d=(6,8)

    とする

In [24]:
# ベクトルの内積
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [25]:
# 行列の積
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

### 配列から別の配列を作る

In [68]:
x = np.array([1,2,3,4,5,6])
print("x = ", x)
print()

# 偶数値をもつ場合は True, 奇数は False の bool 値をもつ配列
print("x%2 == 0 :", x%2 == 0)
print("type(x%2==0) =", type(x % 2 == 0))
print()

# 3より大きい場合は True，3以下の場合は False
print("x > 3 :", x > 3) # [False False False  True  True  True]
print()

# 偶数の場合は "Even", 奇数の場合は "Odd" を要素にもつ配列をつくる
print("np.where(x%2 == 0, 'Even', 'Odd') :", np.where(x%2 == 0, 'Even', 'Odd'))


x =  [1 2 3 4 5 6]

x%2 == 0 : [False  True False  True False  True]
type(x%2==0) = <class 'numpy.ndarray'>

x > 3 : [False False False  True  True  True]

np.where(x%2 == 0, 'Even', 'Odd') : ['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


### ランダムな要素の配列を作る
* https://docs.scipy.org/doc/numpy/reference/routines.random.html
* https://note.nkmk.me/python-numpy-random/

* 様々な分布の乱数を作ることができる
    * 一様分布の乱数生成
        * numpy.random.rand(): 0.0以上、1.0未満
        * numpy.random.random_sample(): 0.0以上、1.0未満
        * numpy.random.randint(): 任意の範囲の整数
    * 正規分布の乱数生成
        * numpy.random.randn(): 平均0、標準偏差1
        * numpy.random.normal(): 任意の平均、標準偏差
    * 二項分布の乱数生成
        * numpy.random.binomial()
    * ベータ分布の乱数生成
        * numpy.random.beta()
    * ガンマ分布の乱数生成
        * numpy.random.gamma()
    * カイ二乗分布の乱数
        * numpy.random.chisquare()

In [87]:
# ランダムな値をもつ4個の要素からなるベクトルを生成
# 値は平均0、標準偏差1の標準偏差をもつ正規分布に従う
b1 = np.random.randn(4)
print("b1 =", b1)
print()

# （10,2）の行列を生成
x = np.random.randn(10,2)
print("x =")
print(x)
print()

# 3以上、5未満の乱数を取得
print("randn(3<=r<5) :", (5 - 3) * np.random.rand() + 3)

b1 = [ 0.65579924  0.1531282  -0.18656358  0.2512131 ]

x =
[[-0.19069458 -0.30022835]
 [ 0.20668796 -0.14204594]
 [-1.50811987  0.64099597]
 [-1.30607681  0.14925832]
 [ 1.19089877 -0.57915184]
 [-1.50098463  0.51237708]
 [ 2.96426386  2.08430497]
 [ 0.22148915  0.2014916 ]
 [ 0.46757095  0.11378885]
 [-1.74011884 -0.03334501]]

randn(3<=r<5) : 3.0304299472750262


### 行列の形状変換

In [108]:
W = np.array([[1,2,3],[4,5,6]])
print("W =")
print(W)
print()

# 多次元配列を1次元配列化
W = W.flatten()
print("W.flatten() =", W)    # [1 2 3 4 5 6]
print("W.shape =", W.shape)  #(6,)
print()

# 1次元配列を2次元配列化
# (6,) を (1,6) へ変換
W = W.reshape(1,6)
print("W.reshape(1,6) =")
print(W)
print("W.shape =", W.shape)
print()

# 行列の形状を変形
# (1,6) を (3,2) へ変換
W = W.reshape(3,2)
print("W.reshape(3,2) =")
print(W)
print("W.shape =", W.shape)

W =
[[1 2 3]
 [4 5 6]]

W.flatten() = [1 2 3 4 5 6]
W.shape = (6,)

W.reshape(1,6) =
[[1 2 3 4 5 6]]
W.shape = (1, 6)

W.reshape(3,2) =
[[1 2]
 [3 4]
 [5 6]]
W.shape = (3, 2)


### ゼロ行列の生成

In [129]:
print("np.zeros(3) = \n{z}\n".format(z=np.zeros(3)))
print("np.zeros((5,3)) = \n{z}\n".format(z=np.zeros((5,3))))
print("np.zeros([3,2]) = \n{z}\n".format(z=np.zeros([3,2])))

W = np.array([[1,2,3],[4,5,6]])
print("W =\n{w}".format(w=W))
print("W.shape = {ws}\n".format(ws=W.shape))

# 指定した配列と同じサイズのゼロ行列を生成
WZ = np.zeros_like(W)
print("WZ = np.zeros_like(W) =\n{wz}".format(wz=WZ))
print("WZ.shape =", WZ.shape)

np.zeros(3) = 
[0. 0. 0.]

np.zeros((5,3)) = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

np.zeros([3,2]) = 
[[0. 0.]
 [0. 0.]
 [0. 0.]]

W =
[[1 2 3]
 [4 5 6]]
W.shape = (2, 3)

WZ = np.zeros_like(W) =
[[0 0 0]
 [0 0 0]]
WZ.shape = (2, 3)


### 配列のインデックスの並び替え

In [3]:
# インデックスを小さい順にソートする
import numpy as np
x = np.array([100, -20, 2])
x.argsort()

array([1, 2, 0])

### 有効数字3桁で表示

In [4]:
np.set_printoptions(precision=3)
x = np.array([1.23456, 2.34567])
print(x)

[1.235 2.346]


### 特異値分解を行う

In [11]:
import numpy as np

W = np.array([
 [0.,    1.807, 0.,    0.,    0.,    0.,    0.   ],
 [1.807, 0.,    0.807, 0.,    0.807, 0.807, 0.   ],
 [0.,    0.807, 0.,    1.807, 0.,    0.,    0.   ],
 [0.,    0.,    1.807, 0.,    1.807, 0.,    0.   ],
 [0.,    0.807, 0.,    1.807, 0.,    0.,    0.   ],
 [0.,    0.807, 0.,    0.,    0.,    0.,    2.807],
 [0.,    0.,    0.,    0.,    0.,    2.807, 0.   ]
])
U, S, V = np.linalg.svd(W)
print('U =')
print(U)
print('S =')
print(S)
print('V =')
print(V)

U =
[[ 3.409e-01  3.331e-16 -1.887e-15 -1.206e-01  1.110e-16 -9.323e-01
  -1.996e-16]
 [ 0.000e+00 -5.975e-01 -1.804e-01  0.000e+00 -7.813e-01  0.000e+00
   0.000e+00]
 [ 4.362e-01  1.665e-16 -8.882e-16 -5.089e-01  6.939e-17  2.253e-01
   7.071e-01]
 [-1.110e-15 -4.977e-01 -6.805e-01  2.637e-16  5.378e-01  5.551e-16
  -8.877e-18]
 [ 4.362e-01  1.564e-16 -8.001e-16 -5.089e-01  6.513e-17  2.253e-01
  -7.071e-01]
 [ 7.094e-01  1.564e-16 -8.001e-16  6.837e-01  6.513e-17  1.709e-01
   2.317e-17]
 [ 1.554e-15 -6.287e-01  7.101e-01 -3.886e-16  3.168e-01 -1.221e-15
   1.143e-17]]
S =
[3.167e+00 3.167e+00 2.703e+00 2.703e+00 1.514e+00 1.514e+00 1.594e-16]
V =
[[-0.000e+00  5.975e-01 -6.661e-16  4.977e-01 -8.327e-16  1.166e-15
   6.287e-01]
 [-3.409e-01  6.661e-16 -4.362e-01  0.000e+00 -4.362e-01 -7.094e-01
   0.000e+00]
 [-1.206e-01 -2.609e-15 -5.089e-01  0.000e+00 -5.089e-01  6.837e-01
   0.000e+00]
 [ 0.000e+00 -1.804e-01  1.943e-16 -6.805e-01  2.637e-16 -3.608e-16
   7.101e-01]
 [-9.323e-01 